x-common:
    &common
    volumes:
        - wordpress_data:/var/www/html
        - ./docker/snapshot:/tmp/snapshot
        - ./origamiez:/var/www/html/wp-content/themes/origamiez
        - ./plugins/craftsman-suite:/var/www/html/wp-content/plugins/craftsman-suite
        - ./docker/config/override.ini:/usr/local/etc/php/conf.d/override.ini
    networks:
        - dev_tools
    logging:
        driver: 'json-file'
        options:
            max-size: '10m'
            max-file: '3'

x-environment:
    &common-env
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    WORDPRESS_CONFIG_EXTRA: |
        define( 'DISABLE_WP_CRON', true );
        define('FS_METHOD', 'direct');

services:
    wordpress:
        <<: *common
        build:
            context: .
            dockerfile: docker/wordpress/Dockerfile
            args:
                WWWUSER: ${WWWUSER:-1000}
                WWWGROUP: ${WWWGROUP:-1000}
        image: tranthethang/calm-canvas-wordpress-php8.3-apache:latest
        restart: unless-stopped
        environment:
            <<: *common-env
            WORDPRESS_DB_CHARSET: ${WORDPRESS_DB_CHARSET}
            WORDPRESS_DB_COLLATE: ${WORDPRESS_DB_COLLATE:-utf8mb4_unicode_ci}
            WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
        ports:
            - '${WP_PORT}:80'
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.origamiez.rule=Host(`origamiez.localhost`)"
            - "traefik.http.routers.origamiez.entrypoints=web,websecure"
            - "traefik.http.routers.origamiez.tls=true"
            - "traefik.http.services.origamiez.loadbalancer.server.port=80"

    cli:
        <<: *common
        build:
            context: .
            dockerfile: docker/cli/Dockerfile
            args:
                WWWUSER: ${WWWUSER:-1000}
                WWWGROUP: ${WWWGROUP:-1000}
        image: tranthethang/calm-canvas-wordpress-php8.3-cli:latest
        user: www-data
        command: tail -f /dev/null
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            <<: *common-env
        labels:
            ofelia.enabled: 'true'
            ofelia.job-exec.wp-cron-task.schedule: '@every 1m'
            ofelia.job-exec.wp-cron-task.command: 'wp cron event run --due-now'
            ofelia.job-exec.wp-cron-task.user: 'www-data'
        depends_on:
            - wordpress

    scheduler:
        image: mcuadros/ofelia:latest
        restart: unless-stopped
        depends_on:
            - cli
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        command: daemon --docker

networks:
    dev_tools:
        external: true

volumes:
    wordpress_data:
