# Global Logging Configuration
x-logging: &common-logging
    logging:
        driver: 'json-file'
        options:
            max-size: '10m'
            max-file: '3'

# Network Configuration
x-networks: &common-networks
    networks:
        - dev_tools

# Essential Volumes for all environments
x-volumes: &common-volumes
    volumes:
        - wordpress_data:/var/www/html
        - ../snapshot:/tmp/snapshot

# Database Connection Environment Variables
x-db-env: &common-db-env
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

# WordPress Core Configuration
x-wp-core-env: &common-wp-env
    WORDPRESS_CONFIG_EXTRA: |
        define( 'DISABLE_WP_CRON', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        @ini_set( 'display_errors', 0 );
        define('FS_METHOD', 'direct');
        if ( isset( $$_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
            $$_SERVER['HTTPS'] = 'on';
        }
        if (isset($$_SERVER['HTTP_HOST'])) {
            $$proto = (isset($$_SERVER['HTTP_X_FORWARDED_PROTO']) && $$_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') ? 'https' : 'http';
            define('WP_HOME', $$proto . '://' . $$_SERVER['HTTP_HOST']);
            define('WP_SITEURL', $$proto . '://' . $$_SERVER['HTTP_HOST']);
        }

services:
    common-base:
        <<: [*common-logging, *common-networks, *common-volumes]
        environment:
            <<: [*common-db-env, *common-wp-env]
